### ISSUE TITLE
Code design and use of globals

### ISSUE THREAD

**Issue by mpmdean** [mpmdean/pyrixs#11]
Use of globals seems reasonable to me, but it is not completely obvious if this is the best design. 

@danielballan

**Comment by danielballan** [comment]
The short answer is, "Trust me, don't use globals." A Google search would turn up plentiful rants about why globals make code difficult to maintain -- in Python or most any language.

I can give more helpful/specific suggestions in the actual code.

**Comment by mpmdean** [comment]
Globals have now been removed.

**Comment by danielballan** [comment]
🎉
