### ISSUE TITLE
Publish documentation

### ISSUE THREAD

**Issue by mpmdean** [mpmdean/pyrixs#18]
I've written an installation guide.

rst is a pain in the arse. I'm running make html about 4 time per line of properly formatted final content...

@danielballan
I you could show me how to publish this somewhere that would be great.

**Comment by danielballan** [comment]
This made me laugh out loud. Yeah... I'm not a fan, but there's nothing else that does what it does. One becomes accustomed to the quirks.

Turn on GitHub's Travis-CI integration (primarily, people use to run tests automatically, but it can also be used to build/publish documentation). And then use doctr to configure Travis to publish the documentation: https://drdoctr.github.io/doctr/

I'm happy to sit down in person and help with that.

**Comment by mpmdean** [comment]
It would be great if you can help with this. I would say we could do this whenever is best for you (either soon or a while down the road) depending on your other commitments.

**Comment by danielballan** [comment]
Next week at this point. Maybe Monday morning on the train if you are on
the train.

**Comment by mpmdean** [comment]
I probably won't be on the train. I'll check with you next week.
Best,
Mark
