### ISSUE TITLE
How to do documentation?

### ISSUE THREAD

**Issue by mpmdean** [mpmdean/pyrixs#9]
Use sphinx?

@danielballan

**Comment by danielballan** [comment]
Yep. Doing the initial configuration is the by far the hardest part. I'd be happy to sit next to you and walk through that sometime.

**Comment by mpmdean** [comment]
Copy formatting from load image

**Comment by danielballan** [comment]
We'll look at this together shortly as planned, but here are some links:

* [numpy docstring standard](https://github.com/numpy/numpy/blob/master/doc/HOWTO_DOCUMENT.rst.txt)
* [bluesky documention source](https://github.com/NSLS-II/bluesky/tree/master/doc/source)
